run:
  concurrency: 4
  timeout: 5m
linters:
  enable:
    - asciicheck
    - dogsled
    - durationcheck
    - exportloopref
    - goconst
    - gocritic
    - nilerr
    - tagliatelle
    - unconvert
    - unparam
    - whitespace
