version: "3.8"

services:
  database:
    container_name: database
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgrespw
      - POSTGRES_DB=main
    ports:
      - "192.168.1.64:5432:5432"
    volumes:
      - db:/var/lib/postgresql/data

volumes:
  db: